#!/bin/zsh
SCRIPT_SOURCE=$(dirname $(readlink -f $0))
source $SCRIPT_SOURCE/antigen-git/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
# antigen bundle git
# antigen bundle heroku
# antigen bundle pip
# antigen bundle lein
# antigen bundle command-not-found
antigen bundle npm
antigen bundle nyan
antigen bundle coffee
antigen bundle cp
antigen bundle catimg
antigen bundle git

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# fancy git prompt
# antigen-bundle arialdomartini/oh-my-git
# antigen theme arialdomartini/oh-my-git-themes oppa-lana-style

antigen bundle rupa/z

# antigen bundle Lokaltog/powerline powerline/bindings/zsh

# Load the theme.
# antigen theme robbyrussell

# Tell antigen that you're done.
antigen apply
